stellar:
  version: v1
  address: localhost:8007
  db:
      - 0.0.0.0:2379 
  syncer: 0.0.0.0:4222
  stopic: collector
  instrument:
    address: 0.0.0.0:4222
    stopic: collector
    collect: 15s
    location: logs/

